version: '3.4'

services:
  trudvang_service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 1337:80
    networks:
      - service_network
    environment:
      WAIT_HOSTS: db:27017
    depends_on:
      - "db"
  db:
    image: mongo:4
    volumes:
      - data
    ports:
      - 27017:27017
    networks:
      - service_network

volumes:
  data:
networks:
  service_network: